piVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
      tier: frontend
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tomcat
        tier: frontend
    spec:
      containers:
        - name: mytomcat
          image: azurek8s.azurecr.io/javahelloworrld:v1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
    tier: frontend  
  ports:
    - port: 8080
  type: LoadBalancer  
