apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat-deployment1
spec:
  selector:
    matchLabels:
      app: tomcat1
      tier: frontend1
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tomcat1
        tier: frontend1
    spec:
      containers:
        - name: mytomcat
          image: azurek8s.azurecr.io/Hello1:v1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service1
spec:
  selector:
    app: tomcat1
    tier: frontend1 
  ports:
    - port: 8080
  type: LoadBalancer 
